[package]
name = "rust-bytes"
version = "0.1.0"
edition = "2024"

[dependencies]
rayon = "1.10.0"
tokio = { version = "1.44.1", features = ["full"] }
color-eyre = "0.6.3"
ulid = "1.2.1"
enumflags2 = "0.7.11"
deref-macro = { path = "../deref-macro" }
